
name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello Alex"
      - name: Printing goodbye
        run: echo "Done - bye"
      - name: Shell commands
        run: |
          echo "First output"
          echo "Second output"
      
